"""empty message

Revision ID: eed903af16a2
Revises: None
Create Date: 2016-03-26 00:28:56.120429

"""

# revision identifiers, used by Alembic.
revision = 'eed903af16a2'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_house_civicNumber'), 'house', ['civicNumber'], unique=False)
    op.create_index(op.f('ix_house_neighbourhoodName'), 'house', ['neighbourhoodName'], unique=False)
    op.create_index(op.f('ix_house_stdStreet'), 'house', ['stdStreet'], unique=False)
    op.create_index(op.f('ix_house_stdStreetSorted'), 'house', ['stdStreetSorted'], unique=False)
    op.drop_column('house', 'createdAt')
    op.drop_column('house', 'updatedAt')
    op.create_unique_constraint(None, 'tree', ['treeID'])
    op.create_foreign_key(None, 'tree', 'house', ['house'], ['id'])
    op.drop_column('tree', 'createdAt')
    op.drop_column('tree', 'updatedAt')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tree', sa.Column('updatedAt', mysql.DATETIME(), nullable=True))
    op.add_column('tree', sa.Column('createdAt', mysql.DATETIME(), nullable=True))
    op.drop_constraint(None, 'tree', type_='foreignkey')
    op.drop_constraint(None, 'tree', type_='unique')
    op.add_column('house', sa.Column('updatedAt', mysql.DATETIME(), nullable=True))
    op.add_column('house', sa.Column('createdAt', mysql.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_house_stdStreetSorted'), table_name='house')
    op.drop_index(op.f('ix_house_stdStreet'), table_name='house')
    op.drop_index(op.f('ix_house_neighbourhoodName'), table_name='house')
    op.drop_index(op.f('ix_house_civicNumber'), table_name='house')
    ### end Alembic commands ###
